Repository mostafa-221/jobcrawler-backend, pull requests merged in 2020-05, with the labels that each got.

#19 added schedueled deleting of jobs if they do not exist
  src/main/java/nl/ordina/jobcrawler/model/Vacancy.java
  src/main/java/nl/ordina/jobcrawler/scrapers/YachtVacancyScraper.java
  src/main/java/nl/ordina/jobcrawler/service/VacancyService.java
  src/main/java/nl/ordina/jobcrawler/service/VacancyStarter.java
Labels: enhancement

#21 changed handling of nr of pages for JobBirdScraper
  src/main/java/nl/ordina/jobcrawler/scrapers/JobBirdScraper.java
Labels: enhancement

#15 Documentation of the heroku server
  docs/deployment.md
Labels: documentation

#29 removed the ConnectionDocumentService
  src/main/java/nl/ordina/jobcrawler/scrapers/HuxleyITVacancyScraper.java
  src/main/java/nl/ordina/jobcrawler/scrapers/JobBirdScraper.java
  src/main/java/nl/ordina/jobcrawler/scrapers/VacancyScraper.java
  src/main/java/nl/ordina/jobcrawler/scrapers/YachtVacancyScraper.java
  src/main/java/nl/ordina/jobcrawler/service/ConnectionDocumentService.java
Labels: code improvement

#31 added scrape method call on startup
  src/main/java/nl/ordina/jobcrawler/service/VacancyStarter.java
Labels: feature

#30 added response status to exceptions and deleted advice classes
  src/main/java/nl/ordina/jobcrawler/controller/advice/VacancyNotFoundAdvice.java
  src/main/java/nl/ordina/jobcrawler/controller/advice/VacancyURLMalformedAdvice.java
  src/main/java/nl/ordina/jobcrawler/controller/exception/SkillNotFoundException.java
  src/main/java/nl/ordina/jobcrawler/controller/exception/VacancyURLMalformedException.java
Labels: code improvement

#33 Create maven.yml
  .github/workflows/maven.yml
Labels: feature, test
